apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-deployment
  labels:
    app: hello-spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring-deployment
  template:
    metadata:
      name: hello-spring-deployment
      labels:
        app: hello-spring-deployment
    spec:
      containers:
        - name: hello-spring-deployment
          image: my-spring-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      
